### ISSUE TITLE
add two new links to the navbar of home.html which should redirect use to thankyou.html and redirected.html

### ISSUE THREAD

**Issue by swarupe7** [swarupe7/MedPlant#16]

**Comment by Naresh-Kushwaha** [comment]
Hi  swarupe7,
I've been looking at the issue #16 and I'm trying to get a clear understanding of the current situation.From what I understand so far, we need to add a link on logo(MedPlant).However, I'm a bit unsure, and I'd appreciate some clarification on that. Could you please provide more information about this issue.
Additionally, if you could share any example or relevant documentation related to this issue, it would be really helpful for me to grasp the context better.

**Comment by swarupe7** [comment]
Hi @Naresh-Kushwaha  for showing your interest in our project.
The logo is already linked , so there is nothing to do with logo . I want you to create two new links at the right most section of navbar , i.e developers ,. Discover which should redirect you to thankyou.html and redirected.html respectively

**Comment by Naresh-Kushwaha** [comment]
Can I use Tailwind CSS ?

**Comment by Naresh-Kushwaha** [comment]
please assign it to me.

**Comment by swarupe7** [comment]
@Naresh-Kushwaha okkk
