### ISSUE TITLE
In the footer of homepage ,i mentioned a link to this repo but it was redirecting to some other page . Can any one correct it.

### ISSUE THREAD

**Issue by swarupe7** [swarupe7/MedPlant#2]

**Comment by subhaDTECH** [comment]
Hey , please assign me this issue I want to work on this .

**Comment by swarupe7** [comment]
>ok @subhaDTECH resolve this issue

**Comment by swarupe7** [comment]
By the way how did you find this repo

**Comment by subhaDTECH** [comment]
By Searching in GitHub search bar.

**Comment by swarupe7** [comment]
Thank you @subhaDTECH  for your contribution . could you give this repo a star so that more people could find it and help our project.
