### ISSUE TITLE
there are in sufficient number of plants in the catalogue .so could anyone add few more plants, use the templates or design of existing plant blogs and just modify their content replace images and link it with detailed.html page 

### ISSUE THREAD

**Issue by swarupe7** [swarupe7/MedPlant#5]

**Comment by Pulkitxm** [comment]
Can I get assigned? let me know how to start.

**Comment by swarupe7** [comment]
hi @Pulkitxm  could you solve issuenumber https://github.com/swarupe7/MedPlant/issues/5 as there are very few plants in our project .
all you have to do is create an individual page for babool and amla you could use aloevera.html for this purpose.
all you have to do is just gather info about those respective plants and use the code of aloevera.html and change the content and images accordingly.
you should also update about this plants in detailed.html

**Comment by onkarsrivastava** [comment]
@swarupe7 sure thing. assign me to it.

**Comment by onkarsrivastava** [comment]
@swarupe7 #5 resolved

**Comment by swarupe7** [comment]
Thanks @onkarsrivastava for your contribution give this repo a star

**Comment by onkarsrivastava** [comment]
Could you add my name and profile link in the Authors.md section.Thanks
