### ISSUE TITLE
Enhance Plant Cards with Specific Plant Information(about) instead of generic sentence.

### ISSUE THREAD

**Issue by piyushbarve98** [swarupe7/MedPlant#53]
Description:
The current implementation of the MedPlant project features cards for various herbal plants, each displaying a name along with a generic sentence in the description. To provide users with more informative content, this issue proposes replacing the generic sentence with specific details about each plant such as about of the page.

Please assign this issue to me or I'll directly submit a PR. I am open to suggestions for it.

![image](https://github.com/swarupe7/MedPlant/assets/69067476/1928288c-b185-4704-9ef9-2623bcc2e3f4)

**Comment by swarupe7** [comment]
@piyushbarve98  okk go ahead

**Comment by piyushbarve98** [comment]
Hii @swarupe7 check this PR - https://github.com/swarupe7/MedPlant/pull/54
