### ISSUE TITLE
could anyone create a simple Thanking page  using HTML,CSS or bootstrap and list the contributors to this repo in them and mention its link  above the footer of the homepage .

### ISSUE THREAD

**Issue by swarupe7** [swarupe7/MedPlant#9]

**Comment by Pulkitxm** [comment]
Can I get assigned? let me know how to start.

**Comment by swarupe7** [comment]
@Pulkitxm  yes you can have this issue all you need to do is make a good thanking file using html css and bootstrap this page must include the names of developers who worked for this project

**Comment by swarupe7** [comment]
@onkarsrivastava  could you do it bro??

**Comment by onkarsrivastava** [comment]
Sure, put all the contributors name in the AUTHORS.md section. i will take it up from there.

**Comment by swarupe7** [comment]
Okk bro

**Comment by swarupe7** [comment]
@onkarsrivastava which company are working in currently

**Comment by onkarsrivastava** [comment]
as of now, i am student looking for jobs.

**Comment by onkarsrivastava** [comment]
@swarupe7 the 3rd link in AUTHORS.md section isn't working. could you correct it?

**Comment by swarupe7** [comment]
Done bro @onkarsrivastava

**Comment by swarupe7** [comment]
@onkarsrivastava thanks bro
